language: python
sudo: false
cache:
  pip: true
  directories:
  - ".venv"

env:
  global:
  - PIP_DEPS="pytest coveralls pytest-cov flake8"

before_install:
- pip install pipenv
- make doctor

python:
- '3.6'

install:
- wget https://downloads.imagej.net/fiji/latest/fiji-linux64.zip
- unzip fiji-linux64.zip
- travis_retry pip install $PIP_DEPS
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .
- make install

script:
- py.test --pyargs diff_classifier --cov-report term-missing --cov=diff_classifier
- make check
- make test

after_success:
- pip install coveralls scrutinizer-ocular
- coveralls
- ocular
