language: python
sudo: false

env:
  global:
  - PIP_DEPS="pytest coveralls pytest-cov flake8"

python:
- '3.6'

script:
- cd $HOME/diff_classifier
- python tests.py

install:
- wget https://downloads.imagej.net/fiji/latest/fiji-linux64.zip
- unzip fiji-linux64.zip
- travis_retry pip install $PIP_DEPS
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
- py.test --pyargs diff_classifier --cov-report term-missing --cov=diff_classifier
