language: python
sudo: false

env:
  global:
  - PIP_DEPS="pytest coveralls pytest-cov flake8"

python:
- '2.7'
- '3.6'

install:
- travis_retry pip install $PIP_DEPS
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
- py.test --pyargs diff_classifier --cov-report term-missing --cov=diff_classifier
